#!/usr/bin/env bash
# TR_TORRENT_NAME is passed automatically by transmission-daemon when it calls
# this script at the end of a download
#TORRENT_DIR="${TR_TORRENT_DIR}"
COMPLETED="${TR_TORRENT_NAME}"
COMPLETED_EXT=${COMPLETED##*.}
DB_FILE="$HOME/.local/share/playlists.db"
TABLE_NAME='animeplaylist'
if [[ "$COMPLETED_EXT" == "mkv" || "$COMPLETED_EXT" == "mkv" ]]; then
    notify-send "Transmission Finished" "$COMPLETED"
    dbmpv "$DB_FILE" $TABLE_NAME --create "$COMPLETED"
fi
