#!/usr/bin/env bash
# Infinite loop printing the list of torrents and their progress
# Use control+C to break the loop
[[ -z $(pgrep transmission) ]] && echo 'Transmission not running' 1>&2 && exit 1

if [[ -n "$1" ]]; then

    case "$1" in

    d) PATTERN="Downloading | Up & Down" ;;
    *) PATTERN="$1" ;;

    esac

    LOOP_COMMAND() { 
        _OUT="$(transmission-remote -l | grep -E "$PATTERN")"
        if [[ -z $_OUT ]]; then
            echo "All Downloads Finished."
            exit
        else 
            echo "$_OUT"
        fi
    }
else
    LOOP_COMMAND() { transmission-remote -l; }
fi

while :; do
    clear
    LOOP_COMMAND
    sleep 3
done
